export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const ADD_COUNTER = "ADD_COUNTER";
export const SUBTRACT_COUNTER = "SUBTRACT_COUNTER";

export const FETCH_COUNTER = "FETCH_COUNTER";
export const FETCH_COUNTER_SUCCESS = "FETCH_COUNTER_SUCCESS";
export const FETCH_COUNTER_ERROR = "FETCH_COUNTER_ERROR";

export const SEND_COUNTER_SUCCESS = 'SEND_COUNTER_SUCCESS';
